[IV 23-24] Objetivo 0
Enaraque/bus_stadistics pull request #1
Opened 2023-09-17 14:19 UTC by Enaraque

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
- Sí, es un problema que puede ser de gran utilidad ya que, en lo personal, me gustaría tener alguna manera de poder ayudar a que las líneas de autobús y sus paradas sean lo más eficientes e ideales posibles.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
- Sí, ya que todos los datos que se generen podrían verlos cualquier usuario así como poder comentar siempre que lo desee. 
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
- Sí, ya que se necesitaría algún algoritmo que, en torno a un comentario, saque conclusiones finales para poder trabajar con ellas.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
- Sí, toda la información necesaria se ha añadido en la carpeta `doc` y se ha enlazado al final del `README`.
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
- El usuario solo necesitaría incluir un comentario con los problemas encontrados en las líneas y/o paradas de autobús.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-17 18:24 UTC, JJ requested changes
En el juego hemos dicho que se describa un problema, y también es lo que dice en el guión. Por favor, trata de entender qué es lo que se pide y, lo más importante, por qué.

2023-09-17 18:24 UTC, JJ commented on README.md
> +Esta aplicación está diseñada para ayudar al ayuntamiento en la gestión efectiva de las líneas y paradas de autobús. Permite a los usuarios informar sobre problemas y errores en las rutas de autobús,
No tienes que describir una aplicación, sino un problema.

2023-09-17 18:24 UTC, JJ commented on README.md
> +## Gráficos y Datos Generados
En desarrollo ágil no puedes *nunca* decir desde el principio lo que quieres hacer.

2023-09-17 20:40 UTC, Enaraque commented
@JJ Listo para revisión

2023-09-18 05:25 UTC, JJ requested changes
Si le hubieras contado esto a un desarrollador/a, ¿qué te habría dicho? Hay que concretar un poco más el problema para poder empezar a solucionarlo a través de un programa.

2023-09-18 05:25 UTC, JJ commented on README.md
> +Soy el encargado del transporte público en el ayuntamiento de mi ciudad. El sistema de transporte público no siempre es perfecto. Siempre pueden surgir diferentes problemas, incluyendo problemas de p
No es un problema suficientemente concreto, más allá de especificar "problemas" y "dificultades". No está claro qué es lo que quiere solucionar, más allá de conocerlos.

2023-09-18 09:35 UTC, Enaraque commented
@JJ  Listo para revisión

2023-09-18 09:43 UTC, JJ requested changes
A veces es un problema poner ejemplos en clase, porque el estudiante entiende que eso es lo que quiero y lo pone directamente en el ejercicio. Pero esto no fue lo que hablamos en clase, ni tiene nada que ver con el ejemplo que te puse (que, dicho sea de paso, sería muy complicado abordar dentro de la asignatura, sobre todo desde que han cortado el API de Twitter).
1. No has identificado bien el cliente. El usuario del autobús puede tener un problema, pero no es un problema que tú puedas solucionar. Quien tiene un problema es quien maneja las líneas de autobús.
2. Como no has identificado bién quién es el cliente, tampoco estás identificando bien la solución, que de todas formas no tendrías que haber puesto: "tener donde quejarse" sería una solución, pero la contribución a la solución del problema es nula.
3. Tal como has formulado la solución, no va más allá de "almacenar y buscar". Se almacena la queja, se recupera el número de quejas y se cuenta. ¿Hallar un porcentaje es una "lógica de negocio adecuada"'? Muy dudoso.

No se me ocurre ninguna modificación, a lo largo de las líneas superiores, que pueda convertir esto en un problema adecuado; y dado que el problema no lo tiene el usuario de la línea sino el ayuntamiento o diputación o quien sea, es muy dudoso que tengas conocimiento personal del mismo salvo que seas pariente del concejal/a de transportes.

2023-09-18 11:01 UTC, Enaraque commented
Entiendo. En ese caso buscaré otro tema del que tenga más conocimiento. @JJ

2023-09-20 21:42 UTC, Enaraque commented
@JJ Listo para revisión

2023-09-21 05:40 UTC, JJ requested changes
Quizás sea conveniente que uses la metodología de design thinking para buscar un problema que sí se pueda abordar en la asignatura. Una vez que tienes el cliente, el resto no debería ser demasiado complicado.

2023-09-21 05:40 UTC, JJ commented on README.md
> +Soy un empresario con una flota de camiones y el gasto operacional principal es el del combustible. Mi problema principal es que me gustaría reducir este gasto pero no tengo visibilidad para saber de
Del [guión del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio), sobre los problemas que no serían adecuados:

> Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información. En general, todo problema que no se entienda bien.

Un poco más abajo, sobre qué lógicas de negocio serían demasiado complejas para este problema:

> Si requiere un modelo complejo del programa, o un algoritmo complejo para trabajar con ella, puede ser un problema, porque, insisto, lo tiene que programar el estudiante. Si requiere predicción y por tanto un algoritmo de machine learning, doble problema, porque requiere conjunto de entrenamiento y programar el algoritmo. Se pueden usar, sin embargo, modelos ya entrenados siempre que esos modelos los programe uno.

2023-09-21 07:24 UTC, Enaraque commented
@JJ He modificado la descripción del objetivo para poder tener una lógica aceptable tal como me dijo en clase.

2023-09-21 11:26 UTC, JJ requested changes
Creo que estamos cerca, pero los aspectos formales de la entrega hay que respetarlos.

2023-09-21 11:26 UTC, JJ commented on README.md
> +Soy un empresario con una flota de camiones y el gasto operacional principal es el del combustible. Mi problema principal es que cuando tengo que llevar pedidos a diferentes destinos no se si es la m
Igual que hemos hablado en clase, tienes que añadir todos los detalles necesarios para que enmarquen el problema. Hace un rato que hemos hablado pero cuando corrija el objetivo 1 miraré el 0 y puedo acordarme o no. Así que, por favor, añade todos los detalles necesarios que más o menos hagan a una persona que no ha hablado contigo entender cuál es el problema y qué pretendes optimizar.

2023-09-21 12:15 UTC, Enaraque commented
@JJ he añadido más detalles a la descripción del problema para intentar que se entienda mejor el problema.

2023-09-21 12:20 UTC, JJ approved these changes
:+1: 

Asegúrate por favor en el objetivo siguiente añadir los detalles que conozcas del problema en las historias de usuario.

2023-09-21 18:19 UTC, merged