[IV-23-24] Objetivo 4
Enaraque/bus_stadistics pull request #28
Opened 2023-11-19 10:44 UTC by Enaraque

2023-11-20 10:08 UTC, puchy22 requested changes
Por lo general parece estar bastante bien trabajado, yo corregiría lo que te he comentado en la review pero en general el código y el test parece correcto. Por añadir algo intenta que los commits sigan siempre las mejores prácticas ya que en este [03b9181](https://github.com/Enaraque/bus_stadistics/pull/28/commits/03b9181c8e9847418010467e3a49a4d1d5ef8ea3) no se siguen y puede dificultar la lectura al saber que hace determinada parte del código.

2023-11-20 10:08 UTC, puchy22 commented on doc/eleccion_herramientas_test.md
> +    trata de una librería externa.
Creo que esto no es lo que estas buscando. Por lo que he estado leyendo es un frameworks de test para la herramienta [denops.vim](https://github.com/vim-denops/denops.vim) que es una herramienta usada para hacer plugins de vim/neovim usando deno.

2023-11-20 10:08 UTC, puchy22 commented on src/asignacionpedidos.ts
> +    constructor() {
Creo que sería más correcto que el constructor recibiese como entrada el nombre de los archivos donde se almacenan los datos o los datos en sí, esto haría que el código fuese reutilizable en un futuro para otros posibles datos.

2023-11-20 10:08 UTC, puchy22 commented on src/data/reparto.json
> +}
La carpeta `data` creo que no debería estar dentro de la que almacena el código fuente.

2023-11-20 10:08 UTC, puchy22 commented on src/asignacionpedidos.ts
> +    extraer_camiones_json(camiones : number[]): Camion[] {
Te recomiendo que revises https://ts.dev/style/#syntax para seguir las mejores prácticas de estilo de TypeScript.

2023-11-20 10:08 UTC, puchy22 commented on src/asignacionpedidos.ts
Por lo general el código parece seguir buenas prácticas en cuanto a modularización pero se podría mejorar en el tema de la sintaxis ya que TypeScripy se suele escribir en estilo CamelCase y en cuanto a la visibilidad de las funciones ya que están todas públicas en la clase cuando muchas, como la extracción de los datos del json o calculos internos, podrían ser privadas ya que no creo que se quieran llamar nunca desde fuera de la propia clase.

2023-11-20 11:05 UTC, Enaraque commented on src/asignacionpedidos.ts
> +    constructor() {
Esto lo estuve hablando con jj porque tuve la misma duda pero me dijo que como estaba hecho no había problema

2023-11-20 11:06 UTC, Enaraque commented on src/data/reparto.json
> +}
Cierto, fallo mío

2023-11-20 12:21 UTC, Enaraque commented
@puchy22 Muchas gracias por dedicarle tiempo a mi repositorio 😄. He arreglado los fallos que me has ido comentando. Échale un vistazo y coméntame que tal te parecen.

Listo para revisión

2023-11-20 16:06 UTC, puchy22 approved these changes
Por mi parte, todo correcto :+1:

2023-11-20 16:11 UTC, Enaraque commented
@JJ Listo para revisión

2023-11-22 07:39 UTC, JJ requested changes
Aparte de las cuestiones de detalle (y no tanto), está el tema principal de que *hay que testear la lógica de negocio*, no que las funciones una vez llamadas dan el resultado esperado.

2023-11-22 07:39 UTC, JJ commented on iv.yaml
> +test: test/asignacion_pedidos.ts
El fichero no se llama así. Este nombre, por cierto, sí sigue las buenas prácticas, el otro no.

2023-11-22 07:39 UTC, JJ commented on src/asignacionpedidos.ts
> +import json from "../data/reparto.json" with { type: "json" };
En código limpio conviene que le asignes siempre nombre significativos. `json` no lo es mucho...

2023-11-22 07:39 UTC, JJ commented on src/asignacionpedidos.ts
> +        const {camiones, envios, distanciaEntreEnvios} = json;
No puedes usar datos estáticos en el código. Entre ese json habrá cosas que sean efectivamente estáticas (entiendo que camiones y distancia entre envíos) pero ¿no sería envíos variable?

2023-11-22 07:39 UTC, JJ commented on test/asignacion_pedidos_test.ts
> +        assertEquals(camionesEnviosAsignadosTest[1][2], 5000);
Estoy revisando los tests, y me cuesta mucho trabajo ver si efectivamente has comprobado que la lógica de negocio funciona. No estás comprobando en ningún lugar que la asignación sea óptima, que es de lo que trata la HU, ¿no?

2023-11-24 12:06 UTC, Enaraque commented
@JJ Listo para revisión 🤞

2023-11-24 13:05 UTC, JJ approved these changes
👍

2023-11-24 18:54 UTC, merged