[IV-23-24] Objetivo 5
Enaraque/bus_stadistics pull request #49
Opened 2023-11-30 08:59 UTC by Enaraque

2023-11-30 09:47 UTC, migueruiz requested changes
Hola @Enaraque seré tu revisor!

2023-11-30 09:47 UTC, migueruiz commented on Dockerfile
> +LABEL version="1.0.0"
Se puede unir todo en un label, no tienes la necesidad de poner dos diferentes. ☝🏼🤓

2023-11-30 10:18 UTC, Enaraque commented on Dockerfile
> +LABEL version="1.0.0"
Tienes razón 🥶, Resuelto en 9d66620aa43ceade4aaf1e4c4e669e5addd090b0

2023-11-30 10:34 UTC, migueruiz approved these changes
Viendo el resto del contenido, creo que esta correctamente todo, poniendo alguna pega más asignar a los diferentes issues que has creado el milestone asociado. Buen trabajo suerte en la revisión! 😄

2023-11-30 11:54 UTC, Enaraque commented
Perfecto! Muchas gracias @migueruiz por el tiempo dedicado 🫶

2023-12-01 12:41 UTC, PabloBarTo approved these changes
Lo he revisado yo también y no encuentro ninguna pega 👌⚡

2023-12-01 13:31 UTC, JJ approved these changes
👍

2024-01-01 23:27 UTC, merged