[IV-23-24] Objetivo 2
Enaraque/bus_stadistics pull request #6
Opened 2023-10-06 07:18 UTC by adelahera

2023-10-06 07:52 UTC, adelahera commented
Por cierto, para incluir el pull request en el repositorio de la asignatura es necesario que le asignes a este pull request un milestone (sino no paso los tests en el repo de la asignatura), dado que yo no tengo permisos para hacerlo. Además, debes asignar también a tu repo el topic de hacktoberfest, así como añadir a este pull request la etiqueta de hacktoberfest-accepted.

2023-10-06 11:01 UTC, Enaraque commented
@adelahera Listo

2023-10-17 18:09 UTC, adelahera commented
Hola @Enaraque . Ya he creado los objetos valor que he considerado necesarios a partir de las historias de usuario, así como una entidad que reúne a estos objetos valor. Si puedes échale un vistazo, por si ves algo que sea susceptible de mejora, o quizá algo en lo que me haya equivocado, o algo que me haya saltado y debería estar implementado.

Muchas gracias.

2023-10-17 19:58 UTC, Enaraque reviewed
Por lo general todo esta como había pensado. Pero faltaría crear otra clase entidad correspondiente a la historia de usuario #4 para una vez obtenidas las asignaciones poder obtener la ruta más óptima.

2023-10-17 19:58 UTC, Enaraque commented on src/AsignacionPedidos.ts
> +    distanciaEntreEnvios: Array<Array<number>>;
En TypeScript hay una manera más sencilla de inicializar matrices:
distanciaEntreEnvios: number[][]

Corrígeme si me equivoco.

2023-10-21 09:18 UTC, adelahera commented
Buenas, @Enaraque . Ya he terminado de crear los diferentes módulos que creo son necesarios para resolver el problema, a partir de los issues generados. Sobre estos, cuando puedas, añade el milestone correspondiente a los issues que no lo tienen añadido. Por último, rellena la lista de comprobación.

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-23 20:35 UTC, Enaraque reviewed
Hola @adelahera, he estado revisando los issues y el código que has hecho. 
Por un lado, el código, quitando pequeños detalles como te he comentado, me parece adecuado. 
Por otro lado, respecto a los issues, veo bien como las haces ya que planteas un problema y lo resuelves con un commit asociado a cada una.

2023-10-23 20:35 UTC, Enaraque commented on src/AsignacionPedidos.ts
> +export declare var maximoEnvios: number;
Esta variable no sería necesaria ya que los envíos máximos que puede tener un camión lo determina la carga máxima de este. Si  la carga está completa o la carga aportada de un envío supera a la carga máxima, no aceptaría más envíos.

2023-10-23 20:37 UTC, Enaraque commented
Otro pequeño apunte. Los nombres de los archivos, para seguir buenas prácticas, deberían ir todo en minúscula ya que hay diversos sistemas de archivos que no las distinguen.

2023-10-24 09:24 UTC, adelahera commented
> Hola @adelahera, he estado revisando los issues y el código que has hecho. Por un lado, el código, quitando pequeños detalles como te he comentado, me parece adecuado. Por otro lado, respecto a los issues, veo bien como las haces ya que planteas un problema y lo resuelves con un commit asociado a cada una.

Genial, pues ya estarían solucionados los problemas que me has comentado. Échale otro vistazo por si ves algún nuevo error y, en caso de que no, lo mando a revisión!

Muchas gracias.

2023-10-24 10:23 UTC, Enaraque commented
Lo veo todo bien :)

2023-10-24 14:01 UTC, adelahera commented
@JJ listo para revisión!

2023-10-25 05:40 UTC, JJ commented
> Lo veo todo bien :)

Tenéis que aprobar explícitamente, siguiendo la lista de comprobación.

2023-10-25 05:41 UTC, JJ commented
> [12780a7](https://github.com/Enaraque/bus_stadistics/commit/12780a7dec64b01dce5dc629f6bdc3d252a4b18c) -> closes #5 [0a2827f](https://github.com/Enaraque/bus_stadistics/commit/0a2827f455d845636430c91fbbc3f9a661563ac8) -> closes #7 [1657a3f](https://github.com/Enaraque/bus_stadistics/commit/1657a3fd8b5c2ededc21910ca9f6fc97c288b766) -> closes #8 [561e42b](https://github.com/Enaraque/bus_stadistics/commit/561e42bc4e459d53152b16f1974446b04e032767) -> closes #9 [d89a54e](https://github.com/Enaraque/bus_stadistics/commit/d89a54ea6e977710d666fe75ea2fc5f309606eb8) -> closes #10 [7af5574](https://github.com/Enaraque/bus_stadistics/commit/7af5574369fea36b040ba79dbd6b63d1a69e2972) -> closes #11 [7260bae](https://github.com/Enaraque/bus_stadistics/commit/7260bae3e5b04597c3173728120b886b1b85cc3b) -> closes #12 [8e2fd78](https://github.com/Enaraque/bus_stadistics/commit/8e2fd78836c3bc9ffea043b916f493a02f35c362) -> closes #13


El PR cierra automáticamente los issues al solucionarse, no hace falta incluir explícitamente el commit que lo hace (aunque deberías haberlo hecho en los mensajes de commit)

2023-10-25 05:42 UTC, JJ commented
La primera línea de este mensaje de commit https://github.com/Enaraque/bus_stadistics/pull/6/commits/1657a3fd8b5c2ededc21910ca9f6fc97c288b766 no aporta ninguna información. El propio mensaje de commit muestra claramente qué es lo que se ha hecho, no repetir la información que ya está en el commit.

2023-10-25 05:48 UTC, JJ commented
> Buenas, @Enaraque . Ya he terminado de crear los diferentes módulos que creo son necesarios para resolver el problema, a partir de los issues generados. Sobre estos, cuando puedas, añade el milestone correspondiente a los issues que no lo tienen añadido. Por último, rellena la lista de comprobación.

Esta lista de comprobación la debe poner @Enaraque cuando revise o eventualmente apruebe el PR.
> 
>     * [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y
>       evidencian comprensión de las historias de usuario? Si no es así, es mejor que
>       se le transmita antes de que empiece a crear cualquier código erróneo.
> 
>     * [x]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
>       comprobación?

Esto:

>  ¿Todos los issues creados están relacionados con a una HU?
> Sí, todos están generados a partir de las HUs.

que @adelahera ha marcado no sucede ni en #5 ni en la #7 . Ninguna de las dos está enlazada con ninguna HU.

2023-10-25 08:21 UTC, adelahera commented
> > [12780a7](https://github.com/Enaraque/bus_stadistics/commit/12780a7dec64b01dce5dc629f6bdc3d252a4b18c) -> closes #5 [0a2827f](https://github.com/Enaraque/bus_stadistics/commit/0a2827f455d845636430c91fbbc3f9a661563ac8) -> closes #7 [1657a3f](https://github.com/Enaraque/bus_stadistics/commit/1657a3fd8b5c2ededc21910ca9f6fc97c288b766) -> closes #8 [561e42b](https://github.com/Enaraque/bus_stadistics/commit/561e42bc4e459d53152b16f1974446b04e032767) -> closes #9 [d89a54e](https://github.com/Enaraque/bus_stadistics/commit/d89a54ea6e977710d666fe75ea2fc5f309606eb8) -> closes #10 [7af5574](https://github.com/Enaraque/bus_stadistics/commit/7af5574369fea36b040ba79dbd6b63d1a69e2972) -> closes #11 [7260bae](https://github.com/Enaraque/bus_stadistics/commit/7260bae3e5b04597c3173728120b886b1b85cc3b) -> closes #12 [8e2fd78](https://github.com/Enaraque/bus_stadistics/commit/8e2fd78836c3bc9ffea043b916f493a02f35c362) -> closes #13
> 
> El PR cierra automáticamente los issues al solucionarse, no hace falta incluir explícitamente el commit que lo hace (aunque deberías haberlo hecho en los mensajes de commit)

En cuanto a esto, en los mensajes de commit, sí que he ido poniendo el issue que cierra cada commit. Sin embargo, pensaba que ponerlos todos los commits en el cuerpo del PR facilitaría el trabajo, pero si es una mala práctica, lo borro.

2023-10-25 08:22 UTC, adelahera commented
> La primera línea de este mensaje de commit [1657a3f](https://github.com/Enaraque/bus_stadistics/commit/1657a3fd8b5c2ededc21910ca9f6fc97c288b766) no aporta ninguna información. El propio mensaje de commit muestra claramente qué es lo que se ha hecho, no repetir la información que ya está en el commit.

Entendido, sí que es verdad que la primera línea simplemente repite el título. ¿Esto ya no se puede arreglar no?

2023-10-25 08:33 UTC, adelahera commented
> > Buenas, @Enaraque . Ya he terminado de crear los diferentes módulos que creo son necesarios para resolver el problema, a partir de los issues generados. Sobre estos, cuando puedas, añade el milestone correspondiente a los issues que no lo tienen añadido. Por último, rellena la lista de comprobación.
> 
> Esta lista de comprobación la debe poner @Enaraque cuando revise o eventualmente apruebe el PR.
> 
> > ```
> > * [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y
> >   evidencian comprensión de las historias de usuario? Si no es así, es mejor que
> >   se le transmita antes de que empiece a crear cualquier código erróneo.
> > 
> > * [x]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
> >   comprobación?
> > ```
> 
> Esto:
> 
> > ¿Todos los issues creados están relacionados con a una HU?
> > Sí, todos están generados a partir de las HUs.
> 
> que @adelahera ha marcado no sucede ni en #5 ni en la #7 . Ninguna de las dos está enlazada con ninguna HU.

Ya he solucionado este error, ahora sí, en cada issue se menciona la historia de usuario que genera el issue.

2023-10-25 08:35 UTC, adelahera commented
Hola, @Enaraque ! Una vez solucionados los pequeños problemas que ha comentado @JJ, ¿puedes volver a seguir la lista de comprobación, tal y como ha dicho, para ver si todo sigue en orden? Te recuerdo que has de poner tu mismo la lista de comprobación.

Muchas gracias!

2023-10-26 08:08 UTC, Enaraque commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-26 08:09 UTC, Enaraque commented
Creo que esta todo bien. 👌

2023-10-26 08:10 UTC, Enaraque commented
@JJ Listo para revisión

2023-10-26 10:27 UTC, JJ commented
En general y en detalle, los commits como este https://github.com/Enaraque/bus_stadistics/commit/e9da79d1b8c3691a41b344af71a7c8b0558485ef siguen las buenas prácticas... Desgraciadamente, no contienen el número del issue con el que se está trabajando. Incluso aunque se esté reaccionando a comentarios, el nuevo código tiene que seguir la historia de usuario y los issues (sólo que mejor); además, eso facilita la labor de quien revisa. Si no es así, tiene uno que navegar por los diferentes commits hasta que encuentra la HU...

2023-10-26 10:34 UTC, JJ requested changes
Me da la impresión de que el enfoque de los issues no es el mismo de #4. La asignación de pedidos no parece que sea un problema; el diseño de las rutas parece ser mucho más importante. Pero en este caso parece que se incluyen datos que puede que no sean relevantes (como la capacidad de un camión, al menos no dice nada en #4) y sin embargo otros que parece que lo serían (como el hecho de que dos destinos estén conectados). Ya te he hecho un comentario en #11, te agradecería que le echaras un vistazo.
(También revisad alternativas a `src` como directorio para alojar los fuentes)

2023-10-26 10:34 UTC, JJ commented on src/ruta.ts
> +    distancias: number[][];
¿Cómo sabes aquí que siempre son los mismos destinos, y si lo son, cuál es el orden?
¿Cómo representas, como dice #4, que dos destinos no estén conectados?
Finalmente, ¿por qué las distancias la gestiona la ruta? ¿No serán las mismas distancias entre destinos independientemente de dónde estén en la ruta?

2023-10-26 20:38 UTC, Enaraque commented
Hola @adelahera, revisando el código me he percatado de que en el archivo `iv.yaml` no has incluido `ruta.ts` como segunda entidad. También, cuando cambiaste el nombre de los archivos, se te olvidó cambiárselo a la entidad que ya hay en `iv.yaml`. 
Siento no haber podido decírtelo antes ya que no me había dado cuenta del error hasta ahora 😅

2023-10-27 08:25 UTC, JJ approved these changes
👍 Yo creo que está bien, salvo lo comentado interface -> type

2023-10-27 08:31 UTC, adelahera commented
Hola, @Enaraque ! @JJ ha dado su aprobación a los cambios implementados. Echa un vistazo por si acaso hubiera algo que se nos ha escapado. Recuerda, antes de hacer merge, asigna el milestone al issue #19, que lo he creado esta misma mañana.

Muchas gracias!

2023-10-27 11:06 UTC, Enaraque commented
👍

2023-10-27 11:07 UTC, Enaraque approved these changes

2023-10-27 11:13 UTC, merged

2024-03-03 17:13 UTC, Gdakgdak22 approved these changes